baseURL = 'https://example.org/'
locale = 'en-es'
title = 'alebozek@wired'
theme = "hugo-theme-console"

[params]
  description = "Geeky computer nerd kind of website"
  animateStyle = "animated zoomIn fast"

[[params.navlinks]]
  name = "/about"
  url = "about/"

[[params.navlinks]]
  name = "/posts"
  url = "posts/"

[[params.navlinks]]
  name = "/pics"
  url = "pics/"
